### ISSUE TITLE
Game should be playable even if not accessed from ticket system

### ISSUE THREAD

**Issue by HelmetRemover** [Midburn/Midburn-Quiz-Frontend#34]
Let's discuss.
The game can be distributed by FB or newsletter, and should be played voluntarily. 
Users will access it and probably will not be identified (not sent with UID).

What should be done at the end of the game?
Currently it is not playable without UID

**Comment by HelmetRemover** [comment]
@natekonimbo 
@omerpines 
Ideas?

**Comment by omerpines** [comment]
If no user ID is provided, at the (successful) end of the game:
1. The user is not returned to Drupal
2. Display a popup message: "Congratulations! You are a bonified burner /
You are ready for Midburn" or something similar + [Share on Facebook] |
[Start over] buttons

**Comment by HelmetRemover** [comment]
1 - fine by me... currently not playable without user ID (a task for @natekonimbo )

2 - Regards your message - the point is "different message than mandatory player". and note we don't have FB share currently, it's "nice to have"

3 - Issue related to @natekonimbo 's comment - 

> we need to test the Pass Test logic against the backend - if we lost drupal's session and need to re-login, does the user input's his login details?
If so, could it be when redirected back to tickets.midburn.org ?

**Comment by omerpines** [comment]
Suggestion:
1. On "Won game", system should send the user to "My Tickets" screen in
Drupal (https://profile.midburn.org/en/user/{UserId}/tickets)
2. If Drupal session is lost, Drupal automatically redirects user to login
screen of Drupal to relogin with parameter in URL to My tickets screen URL
(See above)
3. After the re-login, the user should be automatically directed to the "My
Tickets" screen.

(Need to test this behavior on the Drupal side, I saw it work but just to
be on the safe side...)

**Comment by HelmetRemover** [comment]
OK, my take is like this:
1. currently (identified user) the game makes API call with user id automatically when game is won. The user is not redirected to ticket system unless he clicks a button (but his profile should be updated already).
2. enhancement: unidentified user (lost drupal session during the game or accessed the game not from Drupal [FB, newsletter]) does not make API call automatically, but only when "go to tickets" button is pressed
3. Drupal receives this call and redirects user to login screen of Drupal to relogin [with parameter in URL to My tickets screen]
4. After the re-login, the user should be automatically directed to the "My
Tickets" screen, while his "won game" checkbox is activated.

@natekonimbo 
Please review, does it make sense?

**Comment by tommeir** [comment]
options:
0 - have them signin (using spark api?) at the end of the game to claim their tickets (if they have tickets...) and then pass the uid in the call to drupal.
1 - i expand the drupal game complete api call to support user name parameter as well (that is equals to their email). not all users are signed up for the newsletter with the same mail as their profile, but it would work for 80% of them.
2 - you redirect user to profile login form (can have redirect parameter to my tickets page or other) with a querystring parameter that tells drupal to update user when s\he logs in, we could make something like [DATE][TOKEN][HOUR] send back so that drupal saves that code in user session and after successfull login (within the same date/hour combo) it updates that user profile. its easily hackable, but who cares it will take less time to just complete the games.

**Comment by HelmetRemover** [comment]
I think #2 is what we are looking for?
Omer need tour opinion here

**Comment by omerpines** [comment]
@HelmetRemover + @tommeir , let's keep this simple:
1. Identified user - After finishing the game, 
     a. API call "user won game" is sent.
     b. User clicks button and goes to profile.midburn.org. They will have to go to "My tickets" screen by themselves. 
2. Unidentified user - Since they are not identified, they will first have to log in/sign up to the profile system . 
    1. Display pop up message: To start the game, you first have to login/sign up to your profile at profile.midburn.org (+ button to profile system). 
    2. Add "Game" button to profile system menu (with link games.midburn.org/?uid=XXXX)). 

@HelmetRemover , WDYT?

**Comment by HelmetRemover** [comment]
1 - I believe this part is fully developed. Hope to test tomorrow, as Liad found this flow is not working.
2 - 
i. as long as the login is not on game's side but on profile site.
ii. this is not my call, @omerpines ? and why not create an automatic redirect back to game once user logs in?

**Comment by omerpines** [comment]
2.ii. I will ask @tommeir to add it with the user's UID. 
Automatic redirect - No. There are too many unforeseen use-cases in Drupal which break the logic you expect:
Example 1: User needs to sign terms and conditions first. Not sure system will remember the game afterwards.
Example 2: User does not have a profile and needs to open a profile first. After creating a profile, the user should not be redirected because their profile is not activated until they click the link on the activation email.
These are just off the top of my head. so there will not be an automatic redirect back to the game but the user can choose to go to the game from the menu or when they try to click the view ticket link.

**Comment by HelmetRemover** [comment]
@omerpines @tommeir 
So what's needed on game side is:
a. check if a user attempts to play with active session (logged in to profile system? sends a UID?)
b. if true - we continue as in current version
c. if false - show a message that login is required with a link to profile system.

*Question:* if profile system will be opened in other tab, and after login there, will refreshing game tab check as true (active session)?

**Comment by eladg** [comment]
After a discussion, we decided to set uid to 0 when no uid was provided.

**Comment by mtr574** [comment]
@eladg i got this.

**Comment by mtr574** [comment]
in: `Quiz.js`
```
var userId = config.userId || new URLSearchParams(window.location.search).get('uid') || 0
```

**Comment by mtr574** [comment]
@HelmetRemover check and close
